### ISSUE TITLE
I used the same array, but different result in vs code and your website.

### ISSUE THREAD

**Issue by lixingyangok** [xzitlou/jsontr.ee#10]
![PixPin_2024-12-06_10-02-08](https://github.com/user-attachments/assets/491a8fbc-807c-482d-a451-eb9bd537a245)

**Comment by xzitlou** [comment]
Thanks for letting me know, I have a fix for the library but I didn't push for VS code, I will update today

**Comment by xzitlou** [comment]
@lixingyangok I published the new version, it will be live in 10/15 mins with all the fixes and some improvements
