### ISSUE TITLE
Safari seems to have problem with the node text replacement

### ISSUE THREAD

**Issue by duuri-mollinen** [xzitlou/jsontr.ee#3]
**Describe the bug**
All the text is rendered in single location in the visualization

**To Reproduce**
1. Open the [https://jsontr.ee](https://jsontr.ee) address

**Expected behavior**
Text is rendered in the visualization boxes

**Screenshots**
![image](https://github.com/user-attachments/assets/2a195f1e-37b0-4b6c-b91a-f3eb4a5bd646)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safari
 - Version 18.0.1

**Comment by xzitlou** [comment]
Thanks for letting me know, the issue was fixed.
