### ISSUE TITLE
If JSON Array support

### ISSUE THREAD

**Issue by JavaProgrammerLB** [xzitlou/jsontr.ee#5]
**Is your feature request related to a problem? Please describe.**
- hi, lou, nice to meet you, I found your project jsontree from hacker news, I get a Problem
- when I pass JSON Array in the left of website [jsontr.ee](https://jsontr.ee/), expect to get a Tree in the right, but only get only one Node
```
[
    {
        "by": "luu",
        "descendants": 10,
        "id": 42261707,
        "score": 57,
        "time": 1732759401,
        "title": "Dell is posting unsigned updates to their website which fail to install",
        "type": "story",
        "url": "https://infosec.exchange/@0xabad1dea/113543212666056329"
    },
    {
        "by": "xairy",
        "descendants": 273,
        "id": 42259278,
        "score": 432,
        "time": 1732738255,
        "title": "Malware can turn off webcam LED and record video, demonstrated on ThinkPad X230",
        "type": "story",
        "url": "https://github.com/xairy/lights-out"
    }
]
```
![Xnip2024-11-28_11-54-02](https://github.com/user-attachments/assets/e2e875c1-66f4-4108-a0e2-2e04870d9f32)

**Describe the solution you'd like**
Maybe show the tree with a root node named "array"
![Xnip2024-11-28_11-59-32](https://github.com/user-attachments/assets/524ebe2c-d486-415d-9bc5-c2ebeb6b11cd)

**Comment by xzitlou** [comment]
Hi @JavaProgrammerLB I will check it today

**Comment by xzitlou** [comment]
@JavaProgrammerLB this error should be fixed now 
![Uploading Captura de pantalla 2024-11-29 a la(s) 1.10.50 a. m..png…]()

**Comment by JavaProgrammerLB** [comment]
ok, copy that.
