### ISSUE TITLE
Where to submit PRs for the website at https://jsontr.ee/ ?

### ISSUE THREAD

**Issue by karlhorky** [xzitlou/jsontr.ee#7]
First of all, thanks so much for https://jsontr.ee/ ! It's a great visualization and learning tool, and I'm going to suggest it to our students at https://upleveled.io

**Describe the bug**

I'm looking for a place to submit PRs to the website at https://jsontr.ee/

Is this open source?

**To Reproduce**
1. Find a bug in the website
2. Try to find a place to submit a PR

**Expected behavior**

A public repo exists where users can submit PRs

**Screenshots**

--

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

The first bug that I noticed was the language name "Deutsche" in the language switcher

![Screenshot 2024-12-01 at 13 22 23](https://github.com/user-attachments/assets/449032f5-2f71-4591-bcc3-180b4730281a)

But I'm guessing that there will be more, either spotted by me or by other users

**Comment by xzitlou** [comment]
Hi @karlhorky , thank you so much for your kind words about https://jsontr.ee/! I'm thrilled to hear that you find it useful and are considering recommending it to your students at https://upleveled.io/ – that really means a lot to me.

To answer your question: while the website (https://jsontr.ee/) itself is not open source, my library behind it is. However, any issues or suggestions related to the website can absolutely be commented on here as an issue, and I’d be more than happy to address them or help resolve them.

Regarding the specific bug with the language name “Deutsche” in the language switcher – thank you for pointing that out! I’ve already fixed it. If you find any other bugs or areas for improvement, feel free to let me know here.

I haven’t thought about making the website open source yet, but I’ll definitely consider it. Thanks for bringing it up!
